stages:
  - build

build:
  stage: build
  tags:
  - docker
  image: jshridha/dind
  before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

  script:
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
